import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const fontPath = resolve(root, "src/font/tinyTS.woff2");
const outputPath = resolve(root, "src/render/embeddedFont.ts");
const base64 = readFileSync(fontPath).toString("base64");
const chunks = base64.match(/.{1,96}/g) ?? [];

const source = `// Generated by scripts/embed-font.ts from src/font/tinyTS.woff2.
export const TINYTS_FONT_BASE64 =
${chunks.map((chunk, index) => `    "${chunk}"${index === chunks.length - 1 ? ";" : " +"}`).join("\n")}
`;

writeFileSync(outputPath, source);
